# RabbitMQ constants
RABBITMQ_EXCHANGE_NAME = "trading_bot_exchange"

RABBITMQ_ROUTING_AFK_MODE = "afk_mode"
RABBITMQ_ROUTING_INCOMING_TRADE_REQUEST = "incoming_trade_request"
RABBITMQ_ROUTING_PLAYER_HAS_JOINED_THE_AREA = "player_has_joined_the_area"
RABBITMQ_ROUTING_PLAYER_HAS_LEFT_THE_AREA = "player_has_left_the_area"
RABBITMQ_ROUTING_TRADE_ACCEPTED = "trade_accepted"
RABBITMQ_ROUTING_TRADE_CANCELLED = "trade_cancelled"

RABBITMQ_KILL_ALL_TRADING_BOT_THREADS = "KILL_ALL_TRADING_BOT_THREADS"

# Timers
PLAYER_JOINED_AREA_TRADE_WAIT_TIME = 5
