# RabbitMQ constants
RABBITMQ_EXCHANGE_NAME = "trading_bot_exchange"

RABBITMQ_ROUTING_AFK_MODE = "afk_mode"
RABBITMQ_ROUTING_INCOMING_TRADE_REQUEST = "incoming_trade_request"
RABBITMQ_ROUTING_PLAYER_HAS_JOINED_THE_AREA = "player_has_joined_the_area"
RABBITMQ_ROUTING_PLAYER_HAS_LEFT_THE_AREA = "player_has_left_the_area"
RABBITMQ_ROUTING_NOT_IN_A_PARTY = "not_in_a_party"
RABBITMQ_ROUTING_TRADE_ACCEPTED = "trade_accepted"
RABBITMQ_ROUTING_TRADE_CANCELLED = "trade_cancelled"
RABBITMQ_ROUTING_PLAYER_NOT_FOUND_IN_THIS_AREA = "player_not_found_in_this_area"

RABBITMQ_KILL_ALL_TRADING_BOT_THREADS = "kill_all_trading_bot_threads"

# Trade
PLAYER_PARTY_INVITE_INACTIVITY_TIME = 5
PLAYER_PARTY_INVITE_LOADING_WAIT_TIME = 5
TIMEOUT_BEFORE_TRADE = 5
TRADE_CELL_RETRIES = 15
TRADE_ACCEPTED_WAIT_RETRIES = 15
TRADE_RETRIES = 1
